import random

t1 = ("HEREDITARY\nSYNOPSIS: Hereditary is a 2018 American supernatural psychological horror film written and directed by Ari Aster in his directorial debut. It stars Toni Collette, Alex Wolff, Milly Shapiro, and Gabriel BIyrne as the members of a family haunted by a mysterious presence after the death of their secretive grandmother.\nAUTHOR: Ari Aster\nAVAILABLE IN: Amazon Prime Video, HBO Max, Youtube and Google Play")
t2 = ("THE RITUAL\nSYNOPSIS:A group of friends reunite after a long time to plan a vacation. They finally decide to go on a hiking trip in Sweden (North-West Europe). When one of them is injured, they have no choice but to cut through the forest in order to arrive at the lodge a couple of hours sooner. During a raging rainstorm, they spent the night in a spooky, abandoned house. What awaits them are things they never expect out of this supposedly bonding trip. \nAUTHOR: David Bruckner\nAVAILABLE IN: Amazon Prime Video, Youtube, Google Play and Netflix")
t3 = ("ALIEN\nSYNOPSIS: Alien is a 1979 science fiction horror film directed by Ridley Scott and written by Dan O'Bannon. Based on a story by O'Bannon and Ronald Shusett, it follows the crew of the commercial space tug Nostromo, who, after coming across a mysterious derelict spaceship on an undiscovered moon, find themselves up against an aggressive and deadly extraterrestrial set loose on the Nostromo.\nAUTHOR: Ridley Scott\nAVAILABLE IN: Amazon Prime Video, Youtube and Disney+")
t4 = ("GET OUT !\nSYNOPSIS: The plot follows a young black man (Kaluuya), who uncovers shocking secrets when he meets the family of his white girlfriend (Williams). \nAUTHOR: Jordan Peele\nAVAILABLE IN: Youtube and Google Play")
t5 = ("CANDYMAN\nSYNOPSIS: The film follows a Chicago graduate student completing a thesis on urban legends and folklore, which leads her to the legend of the 'Candyman', the ghost of an African-American artist and the son of a slave who was murdered in the late 19th century for his relationship with the daughter of a wealthy white man. \nAUTHOR: Bernard Rose\nAVAILABLE IN: Amazon Prime Video, Google Play and Youtube")
t6 = ("THE PURGE\nSYNOPSIS: The Purge is a 2013 American dystopian action horror film written and directed by James DeMonaco. The film stars Ethan Hawke, Lena Headey, Adelaide Kane, and Max Burkholder as members of a wealthy family who find themselves endangered by a gang of murderers during the annual Purge, a night during which all crime, including murder, is temporarily legal. \nAUTHOR: James Demonaco\nAVAILABLE IN: Amazon Prime Video and Netflix")
t7 = ("MIDSOMMAR\nSYNOPSIS: The film follows dysfunctional couple Dani and Christian, played by Florence Pugh and Jack Reynor, as they travel to Sweden with a group of friends for a midsummer festival, only to find themselves in the clutches of a sinister Scandinavian pagan cult. \nAUTHOR: Ari Aster\nAVAILABLE IN: Globoplay, Telecine, Amazon Prime Video, Youtube and Google Play")
t8 = ("VACANCY\nSYNOPSIS: A young married couple becomes stranded at an isolated motel and finds hidden video cameras in their room. They realize that unless they escape, they’ll be the next victims of a snuff film.\nAUTHOR: Mark L. Smith\nAVAILABLE IN: Amazon Prime Video")
t9 = ("A QUIET PLACE\nSYNOPSIS: It is about a family of four in a small New York state town who must live life in silence while hiding from creatures that hunt by sound. \nAUTHOR: John Krasinski\nAVAILABLE IN: Globoplay, Telecine, Youtube, Amazon Prime Video and Google Play")
t10 = ("DAWN OF THE DEAD\nSYNOPSIS: A nurse, a policeman, a young married couple, a salesman and other survivors of a worldwide plague that is producing aggressive, flesh-eating zombies, take refuge in a mega Midwestern shopping mall. \nAUTHOR: Zack Snyder\nAVAILABLE IN: Globoplay, Telecine, Google Play and Youtube")
listat = [t1, t2, t3, t4, t5, t6, t7, t8, t9, t10]  # terror

c1 = ("GROWN UPS\nSYNOPSIS: The death of old friends' childhood basketball coach reunites the gang at the same place they held a championship years ago. The friends, accompanied by their wives and children, discover that age is not the same as maturity. \nAUTHOR: Dennis Dugan\nAVAILABLE IN: Netflix, Youtube, Amazon Prime Video and Google Play")
c2 = ("WHITE CHICKS\nSYNOPSIS: Two FBI agent brothers, Marcus and Kevin Copeland, accidentally prevent bad guys from being arrested in a drug bust. As punishment, they are forced to escort a pair of socialites into the Hamptons. However, when the girls discover the agency's plan, they refuse to go. With no options left, Marcus and Kevin decide to pose as the sisters, transforming themselves from African-American men into a pair of blondes. \nAUTHOR: Keenen Ivory Wayans\nAVAILABLE IN: Globoplay, Telecine, Youtube and Google Play")
c3 = ("JUST GO WITH IT\nSYNOPSIS: Unhappy in his attempt at marriage, Danny begins to experience relationships without commitment to circumvent the lack. Thus, he goes on with his life as a successful plastic surgeon, having his best friend Katherine, a single mother of a couple, as his faithful squire. When he meets the young Palmer and passion takes hold of both, he invents, to try to win her over, that he is Katherine's husband, father of the children and that he is going to separate. So begins a true love adventure filled with confusion. \nAUTHOR: Dennis Dugan\nAVAILABLE IN: Netflix, Star+, Amazon Prime Video, Youtube and Google Play")
c4 = ("NEIGHBORS\nSYNOPSIS: A young couple moves to a seemingly quiet neighborhood with their newborn son. But, contrary to the peace they were hoping for, they come across Teddy Sanders, a bohemian neighbor, who leads the young people of the neighborhood in the mess they have created. \nAUTHOR: Nicholas Stoller\nAVAILABLE IN: Globoplay, Amazon Prime Video, Star+, Telecine, Youtube and Google Play")
c5 = ("MR. BEAN'S HOLIDAY\nSYNOPSIS : When London's wet weather becomes unbearable, Mr. Bean decides to go to the French Riviera and have fun in the sun. As usual, his plans don't go the way he wanted. He is mistaken twice: for a kidnapper and for a renowned filmmaker when he arrives with the son of a director and a fledgling actress. Mr. Bean ends up at the Cannes Film Festival. \nAUTHOR: Steve Bendelack\nAVAILABLE IN: Netflix, Youtube, Google Play and Amazon Prime Video")
c6 = ("BIG MOMMA'S HOUSE\nSYNOPSIS: Tough FBI agent goes to extreme lengths to stay on the trail of a violent thief who has escaped from prison. While disguising himself as an obese grandmother with a sharp tongue, he is forced to use every skill he has, from cooking to child care. \nAUTHOR: Raja Gosnell\nAVAILABLE IN: Netflix, Globoplay, Amazon Prime Video and Telecine")
c7 = ("CENTRAL INTELLIGENCE\nSYNOPSIS: Before becoming a CIA agent, Bob was bullied in high school. At the agency, he needs to solve a top-secret case and turns to an old classmate, popular in high school, now an accountant. \nAUTHOR: Rawson Marshall Thurber\nAVAILABLE IN: Netflix, Globoplay, Star+, Amazon Prime Video, Telecine, Youtube and Google Play")
c8 = ("MALL COP\nSYNOPSIS: Paul takes his mall security job very seriously, although most of his colleagues don't. When the mall is robbed, the security guard must use all his skills to fight crime. \nAUTHOR: Waddy Wachtel\nAVAILABLE IN: Netflix, Youtube, Amazon Prime Video and Google Play")
c9 = ("AMERICAN PIE\nSYNOPSIS: Jim Levenstein, Kevin Myers, Oz Ostreicher and Paul Finch are four virgin friends on the eve of prom. In the midst of their failed attempts to have sex with their girlfriends, look at naked women on the internet and even attack a freshly baked pie, the guys make a pact and promise to leave their virginity behind before prom. Now they have 24 hours to fulfill that agreement. \nAUTHOR: Paul Weitz\nAVAILABLE IN: Netflix, Globoplay, Star+, Amazon Prime Video, Telecine, Youtube and Google Play")
c10 = ("MIB: MEN IN THE BLACK\nSYNOPSIS: Kay and Jay, the 'Men in Black', are the biggest secret ever kept in the universe. They are agents of an unofficial government agency and responsible for monitoring all alien encounters on Earth. While investigating a series of extraterrestrial activities, they discover an intergalactic terrorist whose mission is to assassinate two ambassadors from opposite galaxies. \nAUTHOR: Danny Elfman\nAVAILABLE IN: Netflix, HBO Max, Star+, Amazon Prime Video, Youtube and Google Play")
listac = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10]  # comedia


a1 = ("TERMINATOR 2: JUDGMENT DAY\nSYNOPSIS: When a child destined to be a leader is born, he is deprived of the company of his mother, who was considered insane when she spoke of a Terminator coming from the future. In this context, another android appears to kill the child.\nAUTHOR: James Cameron and William Wisher Jr.\nAVAILABLE IN: Youtube and Google Play")
a2 = ("GLADIATOR\nSYNOPSIS:In the last days of Marcus Aurelius' reign, the emperor arouses the ire of his son Commodus by making public his fondness for leaving the throne to Maximus, the commander of the Roman army. Hungry for power, Commodus kills his father, assumes the crown, and orders Maximus' death.\nAUTHOR: David Franzoni\nAVAILABLE IN: Netflix, Globoplay, Star+, Amazon Prime Video, Telecine, Youtube and Google Play")
a3 = ("X-MEN: DAYS OF FUTURE PAST\nSYNOPSIS: In the future, mutants are mercilessly hunted by the gigantic Sentinels. The few survivors must live in hiding, otherwise they will also be killed. They seek a way to prevent mutants from being annihilated. To do so, they need to send Wolverine's consciousness on a journey through time, towards the 1970s. There, he seeks out the still young Xavier and Magneto so that, together, they can prevent this tragic future for mutants from becoming a reality.\nAUTHOR: Chris Claremont.\nAVAILABLE IN: Disney+")
a4 = ("GUARDIANS OF THE GALAXY\nSYNOPSIS: Peter Quill (Chris Pratt) was abducted from Earth as a child. As an adult, he made a career out of marauding and earned the name Star-Lord. When he steals an orb, in which the powerful villain Ronan, of the Kree race, is interested, he becomes sought after by several bounty hunters. To escape danger, Quill joins forces with four out-of-system characters: Groot, a humanoid tree (Vin Diesel), the dark and dangerous Gamora (Zoe Saldana), the trigger-happy raccoon Rocket Racoon (Bradley Cooper) and the vengeful Drax. , the Destroyer (Dave Bautista). But Star-Lord discovers that the stolen sphere has a power capable of changing the course of the universe, and soon the group must protect the object to save the future of the galaxy.\nAUTHOR: Dan Abnett, Andy Lanning\nAVAILABLE IN: Disney+")
a5 = ("JURASSIC WORLD: FALLEN KINGDOM\nSYNOPSIS: IIn Jurassic World: Fallen Kingdom, three years after the closure of Jurassic Park, a volcano about to erupt puts life on Isla Nublar at risk. With no human presence and with the dinosaurs living freely, a decision has to be made: should you return to the island to save the animals or abandon them to a new extinction?\nAUTHOR: Michael Crichton.\nAVAILABLE IN: Amazon Prime Video, Youtube and Google Play")
a6 = ("BLACK PANTHER\nSYNOPSIS: : In Black Panther, after the death of King T'Chaka, Prince T'Challa returns to Wakanda for the coronation ceremony. It brings together the five tribes that make up the kingdom, one of which, the Jabari, does not support the current government. Together they are looking for Ulysses Klaue, who stole a handful of vibranium from Wakanda a few years ago.\nAUTHOR: Stan Lee, Jack Kirby\nAVAILABLE IN: Disney+")
a7 = ("LOGAN\nSYNOPSIS: In 2029, Logan (Hugh Jackman) makes a living as a limousine chauffeur to care for the nonagenarian Charles Xavier (Patrick Stewart). Physically weakened and emotionally drained, he is sought out by Gabriela (Elizabeth Rodriguez), a Mexican woman who needs the help of the ex-X-Men to defend little Laura Kinney / X-23 (Dafne Keen). While refusing to return to active duty, Logan is pursued by mercenary Donald Pierce (Boyd Holbrook), who is interested in the gir\nAUTHOR: James Mangold, Mark Millar\nAVAILABLE IN: Star+")
a8 = ("LAW ABIDING CITIZEN\nSYNOPSIS: Clyde Shelton is a devoted family man who witnesses the murder of his wife and daughter. One of the culprits gets only 5 years in prison thanks to a deal made by prosecutor Nick Rice, who believes it's better to get some justice than the chance to get none. Ten years later, the killer is found dead. Even without having enough evidence against him, Clyde is arrested for what happened. Its main objective is to denounce the inconsistency of the judicial system\nAUTHOR: Kurt Wimmer\nAVAILABLE IN: Amazon Prime Video")
a9 = ("THE HUNGER GAMES: CATCHING FIRE\nSYNOPSIS: The saga narrates the adventure of Katniss, a young woman chosen to participate in the 'hunger games', a kind of reality show in which a teenager from each district of Panem must fight with the others until only one comes out alive. In this episode of the series, Katniss must face strong reprisals from the local government, fighting not only for her life, but for the entire population of Panem\nAUTHOR: Suzanne Collins\nAVAILABLE IN: HBO Max, Amazon Prime Video, Youtube and Google Play")
a10 = ("JOHN WICK: CHAPTER 3 – PARABELLUM\nSYNOPSIS: After murdering Mafia boss Santino D'Antonio (Riccardo Scamarcio) at the Continental Hotel, John Wick (Keanu Reeves) is pursued by members of the High Dome for a reward of $14 million. Now, he must join forces with former partners who have helped him in the past as he fights for his survival. \nAUTHOR: Derek Kolstad\nAVAILABLE IN: Globoplay, Telecine, Amazon Prime Video, Youtube and Google Play")
listaa = [a1, a2, a3, a4, a5, a6, a7, a8, a9, a10]  # acao

r1 = ("LOVE, ROSIE\nSYNOPSIS: Alex and Rosie are inseparable friends who grew up together in London, sharing among their best experiences. Everything changes when Alex wins a scholarship and moves to the USA. Separated, their paths are now different. But in today's times it's impossible not to connect. And when it comes to love, it's hard to make the right choices.\nAUTHOR: Cecelia Ahern\nAVAILABLE IN: Amazon Prime Video, Youtube and Google Play")
r2 = ("FIVE FEET APART\nSYNOPSIS: Two cystic fibrosis patients fall in love, despite hospital rules stating that they must keep 1.5 meters apart.\nAUTHOR: Rachael Lippincott, Mikki Daughtry, Tobia Iaconis\nAVAILABLE IN: Globoplay, Telecine, Youtube and Google Play")
r3 = ("MADE OF HONOR\nSYNOPSIS: Suddenly realizing he loves his platonic best friend, a perennial skirt-chaser uses his role as her “maid” of honor to unravel her marriage plans. \nAUTHOR: Adam Sztykiel, Deborah Kaplan, Harry Elfont\nAVAILABLE IN: Netflix, Youtube, Amazon Prime Video and Google Play")
r4 = ("YOUR EYES TELL\nSYNOPSIS: A woman who lost her sight in an accident and an ex-kickboxer with a dark past find solace in each other, even as the past threatens to tear them apart.\nAUTHOR: Takahiro Miki\nAVAILABLE IN: Netflix")
r5 = ("YOUR NAME\nSYNOPSIS: Mitsuha’s the daughter of the mayor of a small town, but dreams of trying her luck in Tokyo. Taki works at a restaurant in Tokyo and wants to quit his job. The two don’t know each other, but are connected by the images of their dreams.\nAUTHOR: Makoto Shinkai\nAVAILABLE IN: Youtube and Google Play")
r6 = ("PRIDE & PREJUDICE\nSYNOPSIS: In Jane Austen’s tale of 19th-century England, Mrs. Bennet hopes to marry her daughters to prosperous gentlemen, including new arrival Mr. Darcy.\nAUTHOR: Deborah Moggach\nAVAILABLE IN: Netflix, Amazon Prime Video, Youtube and Google Play")
r7 = ("ME BEFORE YOU\nSYNOPSIS: From modest origins and without great aspirations, the peculiar Louisa Clark is hired to care for Will, a depressive and cynical young quadriplegic.\nAUTHOR: Jojo Moyes\nAVAILABLE IN: Amazon Prime Video, Youtube and Google Play")
r8 = ("SILVER SKATES\nSYNOPSIS: On the frozen rivers and canals of St. Petersburg, a petty thief on skates warms the heart of an aristocrat’s daughter as forces try to keep them apart.\nAUTHOR: Roman Kantor\nAVAILABLE IN: Netflix")
r9 = ("JUST GO WITH IT\nSYNOPSIS: After spending years pretending to be married, an unattached plastic surgeon meets The One — and enlist his assistant to pose as his soon-to-be wife.\nAUTHOR: Alan Loeb, Timothy Dowling \nAVAILABLE IN: Netflix, Star+, Amazon Prime Video, Youtube and Google Play")
r10 = ("TWILIGHT\nSYNOPSIS: When Bella Swan moves in with her father, she starts school and meets Edward, a mysterious classmate who reveals himself to be a 108-year-old vampire.\nAUTHOR: Melissa Rosenberg\nAVAILABLE IN: Netflix, HBO Max, Globoplay, Star+, Amazon Prime Video, Telecine, Youtube and Google Play")
listar = [r1, r2, r3, r4, r5, r6, r8, r9, r10]  # romance

d1 = ("THE GODFATHER\nSYNOPSIS A mafia family struggles to establish its supremacy in the United States after World War II. An assassination attempt on the boss Vito Corleone incapacitated and forced Michael Sonny to take over the business.\nAUTHOR:Mario Puzo\nAVAILABLE IN: Amazon Prime Video")
d2 = ("SCHINDLER'S LIST\nSYNOPSIS: The German Oskar Schindler saw Jewish labor as a cheap and viable solution for profiting from business during the war. With his strong influence within the Nazi party, it was easy to get permits and open a factory. What might seem like the attitude of a not very kind man turned into one of the greatest love affairs for life in history, as this German gave up all his fortune to save the lives of more than a thousand Jews in the middle of the fight against German extermination \nAUTHOR: Thomas Keneally\nAVAILABLE IN: Google Play, Amazon Prime Video and Youtube")
d3 = ("A DREAM OF FREEDOM\nSYNOPSIS: After a few years in prison Stickan comes out and tries to re-adjust to society. He is approached by his old prison buddy Janne who is full of ideas on how to get money without having to work.\nAUTHOR: Diane McWhorter\nAVAILABLE IN: Globoplay, Amazon Prime Video, Telecine, Youtube and Google Play")
d4 = ("LIFE IS BEAUTIFUL\nSYNOPSIS: During World War II in Italy, the Jew Guido and his son Giosué are taken to a Nazi concentration camp. Away from the woman, he has to use his imagination to make the boy believe that they are participating in a great game, in order to protect him from the terror and violence that surround them.\nAUTHOR: Roberto Benigni / Vincenzo Cerami\nAVAILABLE IN: Amazon Prime Video and Youtube")
d5 = ("THE SHAWSHNK REDEMPTION\nSYNOPSIS: In 1946, Andy Dufresne (Tim Robbins), a young and successful banker, has his life radically changed when he is convicted of a crime he never committed, the murder of his wife and her lover. He is sent to a prison that is every inmate's nightmare, Shawshank State Penitentiary, Maine. There he will serve his life sentence. Andy will soon be introduced to Warden Norton (Bob Gunton), the corrupt and ruthless prison guard who uses the Bible as a weapon of control, and Captain Byron Hadley (Clancy Brown) who treats inmates like animals. Andy befriends Ellis Boyd Redding (Morgan Freeman), a prisoner who has served 20 years and controls the institution's black market.\nAUTHOR: Stephen King\nAVAILABLE IN: Netflix, HBO Max, Amazon Prime Video, Youtube and Google Play")
d6 = ("MEN OF HONOR\nSYNOPSIS:Carl Brashear, a young black man, joins the US Navy in his 50s, a time when racism prevailed in the country. The young man faces prejudice from his white peers and his instructor, but his courage and determination earn him the respect of all.\nAUTHOR: Scott Marshall Smith\nAVAILABLE IN: Amazon Prime Video, Star+, Google Play and Youtube")
d7 = ("FIGTH CLUB\nSYNOPSIS:A depressed man suffering from insomnia meets a strange salesman named Tyler Durden and finds himself living in a dirty house after his perfect apartment is destroyed. The duo form a club with strict rules where men fight. The perfect partnership is compromised when one woman, Marla, attracts Tyl's attention.\nAUTHOR: Chuck Palahniuk\nAVAILABLE IN: Netflix, Star+, Amazon Prime Video and Telecine")
d8 = ("SAVING PRIVATE RYAN\nSYNOPSIS:Upon landing in Normandy, on June 6, 1944, Captain Miller receives the mission of commanding a group of the Second Battalion to rescue soldier James Ryan, the youngest of four brothers, three of whom died in combat. On orders from Chief George C. Marshall, they must search for the soldier and ensure he returns home alive.\nAUTHOR: Robert Rodat\nAVAILABLE IN: Netflix, HBO Max, Globoplay, Amazon Prime Video, Youtube and Google Play")
d9 = ("GLADIATOR\nSYNOPSIS: Maximus is a powerful Roman general, loved by the people and the Emperor Marcus Aurelius. Before his death, the Emperor arouses the ire of his son Commodus by making public his predilection to leave the throne to Maximus. Power-hungry, Commodus kills his father, assumes the crown, and orders the death of Maximus, who manages to escape before being caught, and goes into hiding as a slave and gladiator while seeking revenge.\nAUTHOR:David Franzoni\nAVAILABLE IN: Netflix, Globoplay, Star+, Amazon Prime Video, Telecine, Youtube and Google Play")
d10 = ("HARRIET\nSYNOPSIS: Shortly after having escaped slavery, Harriet Tubman decides to help hundreds of slaves flee the South of the United States during the American Civil War, in the year 1849. Her actions give a new direction to history, and the political activist becomes a of the country's greatest heroes.\nAUTHOR: Gregory Allen Howard\nAVAILABLE IN: Amazon Prime Video, Youtube and Google Play")
listad = [d1, d2, d3, d4, d5, d6, d7, d8, d9, d10]  # drama

av1 = ("PIRATES OF THE CARIBBEAN\nSYNOPSIS:Pirates of the Caribbean (bra: Pirates of the Caribbean; prt: Pirates of the Caribbean) is a fantasy adventure film series, based on the Pirates of the Caribbean toy from Walt Disney Parks and Resorts theme parks started in 2006, directed by Gore Verbinski and Rob Marshall, written by Terry Rossio and Ted Elliott, and produced by Jerry Bruckheimer, about the adventures of Captain Jack Sparrow (Johnny Depp) and other characters such as, Will Turner (Orlando Bloom), Elizabeth Swann (Keira Knightley) , Captain Hector Barbossa (Geoffrey Rush), Joshamee Gibbs (Kevin McNally), Davy Jones (Bill Nighy), Angelica (Penélope Cruz) and Blackbeard (Ian McShane).\nAUTHOR:Terry Rossio and Ted Elliott.\nAVAILABLE IN: Disney+ and Telecine")
av2 = ("AVENGERS\nSYNOPSIS: After Thanos eliminates half of the living creatures in the entire universe, the surviving heroes must deal with the pain of losing friends and loved ones.  With Tony Stark wandering lost in space without food or water, Steve Rogers and Natasha Romanov must lead the resistance against the titan.\nAUTHOR:Anthony Russo/ Joe Russo\nAVAILABLE IN: Disney+")
av3 = ("SPIDER-MAN: NO WAY HOME\nSYNOPSIS: Spider-Man must deal with the consequences of his true identity being discovered.\nAVAILABLE IN: Amazon Prime Video, Youtube and GooglePlay")
av4 = ("WONDER WOMAN\nSYNOPSIS: Trained from an early age to be an unbeatable warrior, Diana Prince has never left the island paradise where she is recognized as a princess of the Amazons.  When pilot Steve Trevor has an accident and crashes on a local beach, she discovers that an unprecedented war is raging across the world and decides to leave her home certain she can stop the conflict.  Struggling to end the war, Diana realizes the scope of her powers and her true mission on Earth.\nAUTHOR: Patty Jenkins\nAVAILABLE IN: HBO Max, GooglePlay and Telecine")
av5 = ("VENOM\nSYNOPSIS: Journalist Eddie Brock develops superhuman strength and power when his body merges with the alien Venom.  Overwhelmed with rage, Venom tries to control Eddie's dangerous new abilities.\nAUTHOR: Todd McFarlane\nAVAILABLE IN: Amazon Prime Video, HBO Max, Youtube and GooglePlay")
av6 = ("THOR: RAGNAROK\nSYNOPSIS: Thor (Chris Hemsworth) must stop Ragnarok, the destruction of his home, Asgard, which is now under the power of the dreaded Hela (Cate Blanchett).  But the problem is that he's stuck on the other side of the universe, without his hammer, and he still has to face his former ally and avenger, Hulk, in a gladiator battle.\nAUTHOR: Eric Pearson\nAVAILABLE IN: Disney+")
av7 = ("FAST AND FURIOUS 8\nSYNOPSIS: Dom Toretto (Vin Diesel) and his crew keep slaying in their tuned cars.  But the mysterious Cipher (Charlize Theron) convinces Dom to return to life as an outlaw.  Now, the team must settle the score with Dom as they try to figure out why he betrayed his family's trust.\nAUTHOR: Chris Morgan\nAVAILABLE IN: Globoplay, Amazon Prime Video, YouTube and GooglePlay")
av8 = ("THE LOST CITY\nSYNOPSIS: Brilliant but reclusive author Loretta Sage (Sandra Bullock) writes about exotic places in her popular adventure novels, whose covers star the handsome model Alan (Channing Tatum), who has dedicated his life to impersonating the hero, Dash.  During the tour promoting her new book with Alan, Loretta is kidnapped by an eccentric billionaire (Daniel Radcliffe) so she can guide him to the treasure of the lost city described in her recent book.  In order to prove that it's possible to be a hero in real life, not just in the pages of her books, Alan sets out to rescue her.  Forced to live an epic jungle adventure, the unlikely pair must work together to survive and find the ancient treasure before it is lost forever.\nAUTHOR: Seth Gordon / Oren Uziel\nAVAILABLE IN: Paramount+")
av9 = ("DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS\nSYNOPSIS: In Doctor Strange in the Multiverse of Madness, after defeating Dormammu and facing Thanos in the events of Avengers: Endgame, the Sorcerer Supreme, Stephen Strange (Benedict Cumberbatch), and his partner Wong (Benedict Wong), continue their research on the Stone of Time.  But an old friend turned enemy puts an end to his plans and causes Strange to unleash unspeakable evil, forcing him to face a powerful new threat.  The film connects with the Disney+ series WandaVision and also has a relationship with Loki.  The feature belongs to phase 4 of the MCU where the reality of the universe can collapse because of the same spell that brought the villains of the Web to the world of the Avengers and the Sorcerer Supreme will need to count on the help of Wanda (Elizabeth Olsen), who lives in isolation since the events of WandaVision.\nAUTHOR:Michael Waldron / Stan Lee\nAVAILABLE IN: Disney+")
av10 = ("MAZE RUNNER: THE DEATH CURE\nSYNOPSIS: In the third film in the saga, Thomas (Dylan O'Brien) embarks on a quest to find a cure for a deadly disease and discovers that C.R.U.E.L's plans could have catastrophic consequences for humanity.  Now, he has to decide if he will turn himself in to the C.R.U.E.L and trust the organization's promise that this will be his last experiment.\nAUTHOR: James Dashner / T.S.  nowlin\nAVAILABLE IN: Amazon Prime Video, Star+ and Disney+")
listaav = [av1, av2, av3, av4, av5, av6, av7, av8, av9, av10]  # aventura

f1 = ("THE ADAM PROJECT\nSYNOPSIS: A time traveler goes back to the year 2022 by accident and ends up meeting his younger self.  Together, and being hunted by forces from the future, the two embark on a quest to fix the timeline and save their loved ones.\nAUTHOR: Jonathan Tropper; Jennifer Flackett; T.S. Nowlin e Mark Levin\nAVAILABLE IN: Netflix")
f2 = ("THE TOMORROW WAR\nSYNOPSIS: The world is shocked when a group of time travelers arrive in 2051 to deliver an urgent message: thirty years in the future, humanity is losing a global war against a deadly alien species.\nAUTHOR: ZACH DEAN\nAVAILABLE IN: Amazon Prime Video")
f3 = ("INTERSTELLAR\nSYNOPSIS: Earth's natural reserves are coming to an end and a group of astronauts is given the mission to check possible planets to receive the world's population, enabling the continuation of the species.  Cooper is called to lead the group and accepts the mission knowing he may never see his children again.  Alongside Brand, Jenkins and Doyle, he will continue in search of a new home.\nAUTHOR: Christopher Nolan e Jonathan Nolan\nAVAILABLE IN:  HBO Max, Youtube, Amazon Prime Video and Google Play")
f4 = ("A QUIET PLACE\nSYNOPSIS: The old adage “children should be seen and not heard” has never been more true than in John Krasinski’s A Quiet Place. It isn’t a dismissive complaint from annoyed grownups; it is the key to survival against alien invaders. The first sound we hear in the film is a happy one, a kid’s toy space shuttle beaming waves of sonic joy on a bridge in the woods. It is the last noise the child will ever hear, and his helpless parents can’t even gasp in shock, or they will also be dragged into the fatal unknown. The silence is almost deafening in the 90-minute film, which only has about five minutes of dialogue. The first words are spoken about 40 minutes into the film.\nAUTHOR: Scott Beck e Bryan Woods\nAVAILABLE IN: Globoplay, Telecine, Youtube, Amazon Prime Video and Google Play")
f5 = ("SNOWPIERCER\nSYNOPSIS:In a frozen world, the last inhabitants of Earth struggle to live in a complex society inside a train that is in constant motion.\nAUTHOR:Jean-Marc Rochette; Jacques Lob e Benjamin Legrand\nAVAILABLE IN: Amazon Prime Video, Globoplay and Netflix")
f6 = ("LUCY\nSYNOPSIS: Lucy is forced to smuggle drugs into her stomach.  But the young woman's body absorbs the substances and she has superpowers, such as telepathy, telekinesis, the absence of pain and the ability to acquire knowledge instantly.\nAUTHOR: Luc Besson\nAVAILABLE IN: Netflix, Star+, Amazon Prime Video, Youtube and Google Play")
f7 = ("COLOSSAL\nSYNOPSIS: Gloria discovers she is connected to a gigantic creature that is destroying Seoul and must discover why her seemingly insignificant existence has such a colossal impact on the fate of Earth.\nAUTHOR: Nacho Vigalondo\nAVAILABLE IN: Youtube and Google Play")
f8 = ("BLADE RUNNER 2049\nSYNOPSIS: After uncovering a secret that threatens what remains of society, a new police officer sets out to find Rick Deckard, who has been missing for 30 years.\nAUTHOR: Hampton Fancher\nAVAILABLE IN: Netflix, Amazon Prime Video, Youtube and Google Play")
f9 = ("UNDER THE SKIN\nSYNOPSIS: A beautiful woman with black hair and red lips seduces the lonely men she meets on her way.  No one imagines that under her skin lurks a dangerous alien that can end lives to fulfill the wishes of her species.\nAUTHOR: Michel Faber\nAVAILABLE IN: Amazon Prime Video")
f10 = ("MOON\nSYNOPSIS: Astronaut Sam Bell's three-year shift at a lunar mine is finally ending and he's looking forward to his reunion with his wife and daughter.  Suddenly, Sam's health takes a turn for the worse.  He suffers from headaches and hallucinations and almost has a fatal accident.  He meets what appears to be a younger version of himself, possibly a clone.  Sam needs to solve the mystery before the company crew arrives.\nAUTHOR: Duncan Jones\nAVAILABLE IN: Netflix")
listaf = [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10]  # ficcao

fa1 = ("ETERNALS\nSYNOPSIS: The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite to battle the evil Deviants. \nAUTHOR: Ryan Firpo and Kaz Firpo\nAVAILABLE IN: Disney+")
fa2 = ("DON'T KNOCK TWICE\nSYNOPSIS: A mother desperate to reconnect with her troubled daughter finds herself embroiled in the urban legend of a demonic witch. \nAUTHOR: Caradog James\nAVAILABLE IN: Amazon Prime Video")
fa3 = ("A NIGHT AT THE MUSEUM\nSYNOPSIS: Dreamer Larry Daley thinks he's destined for something big but his imaginative ideas never pay off and in desperate need of a job, he accepts to be a security guard at the Natural History Museum. During his watch, Larry makes a startling discovery. Thanks to the unleashing of an Egyptian curse, the museum's animals spring to life after the building closes. Larry must find a way to save the chaotic situation. \nAUTHOR: Thomas Lennon, Robert Ben Garant, Milan Trenca\nAVAILABLE IN: Disney+.")
fa4 = ("THE HOME OF PECULIAR CHILDREN\nSYNOPSIS: After the strange death of his grandfather (Terence Stamp), young Jake (Asa Butterfield) leaves with his father for Wales. There he intends to meet Ms. Peregrine (Eva Green), responding to her grandfather's last request, who told her that 'she will tell you everything'. However, when he arrives, he discovers that the place where she would live is a dilapidated mansion, which was hit by a missile during World War II. While investigating the area, Jake discovers that there is a time rift there, where Ms. Peregrine lives and protects several children with special powers. \nAUTHOR: Ransom Riggs\nAVAILABLE IN: Google Play")
fa5 = ("FULL MOON\nSYNOPSIS: On vacation, bored and desperate to get out of his town, Jamie (Ed Speleers) is excited to meet the sexy Juliana (Jessica Szohr), an American tourist. Along with the girl's arrival, however, several strange things begin to happen in the place, such as mysterious disappearances. \nAUTHOR: Luigi Batzella, Ralph Zucker, Walter Brandi, Ian Danby\nAVAILABLE IN: Youtube.")
fa6 = ("FANTASTIC BEASTS: THE CRIMES OF GRINDELWALD\nSYNOPSIS: Newt Scamander (Eddie Redmayne) is reunited with dear friends Tina Goldstein (Katherine Waterston), Queenie Goldstein (Alison Sudol) and Jacob Kowalski (Dan Fogler). He is recruited by his former professor at Hogwarts, Albus Dumbledore (Jude Law), to face the terrible dark wizard Gellert Grindelwald (Johnny Depp), who has escaped from MACUSA (Magical Congress of the USA) and gathers a following, dividing the world. between pure-blood mage beings and non-magical beings. \nAUTHOR: J. K. Rowling\nAVAILABLE IN: HBO Max, Amazon Prime Video, Youtube and Google Play.")
fa7 = ("PRIDE AND PREJUDICE AND ZOMBIES\nSYNOPSIS: England, 19th century. A mysterious plague spreads zombies everywhere, but Elizabeth Bennett (Lily James), an expert in martial arts and weapons handling, is prepared to face the worst undead. What really bothers her is having to live and fight alongside the arrogant Mr. Darcy (Sam Riley). \nAUTHOR: Jane Austen\nAVAILABLE IN: Netflix, Amazon Prime Video, Youtube and Google Play.")
fa8 = ("SEVENTH SON\nSYNOPSIS: John Gregory (Jeff Bridges) is the seventh son of the seventh son and keeps an 18th century town relatively well and away from evil spirits. However, he is no longer young and his attempts to train a successor have all been unsuccessful. His last hope is a boy named Thomas Ward (Ben Barnes), the son of a young farmer. His first challenge will be a big one: he will have to face Mother Malkin (Julianne Moore), a terrible and powerful witch, who escaped her confinement when the grandmaster Gregory was away from the city. \nAUTHOR: Joseph Delaney\nAVAILABLE IN: Netflix, Amazon Prime Video, Youtube and Google Play.")
fa9 = ("SHANG-CHI AND THE LEGEND OF THE TEN RINGS\nSYNOPSIS: Shang-Chi and The Legend of The Ten Rings\nAUTHOR: Destin Daniel Cretton, David Callaham and Andrew Lanham\nAVAILABLE IN:  Disney+.")
fa10 = ("CRANSTON ACADEMY: MONSTER ZONE\nSYNOPSIS: A smart 15-year-old high school student is unexpectedly transferred to a boarding school where a monster portal from another dimension opens. \nAUTHOR: José C. Garcia de Letona and Rita Street\nAVAILABLE IN: Amazon Prime Video.")
listafa = [fa1, fa2, fa3, fa4, fa5, fa6, fa7, fa8, fa9, fa10]  # fantasia
cont = "y"

print("Hello user, I'm Yoda. Welcome to the bright side of the force!\n")

usuario = input('Young person, how may I call you?: ')
print("\n" + usuario + ", It's very nice to meet you. Let's get it started!\n")

usuarioId = float(input("How old are you? "))

if usuarioId < 18:
    {
        print("\nOh, I see you still have a lot to learn! You are too young to be a Jedi, young Padawan!")
    }
elif usuarioId >= 18:
    {
        print("\nYou grew up young Padawan, or should I say young Jedi!")
    }

while cont == "y" or cont == "Y" or cont == "yes" or cont == "Yes" or cont == "YES":

    print("\nNow I'll tell you a hobby that I have and almost no one knows about it... Watching movies! So please select your favorite genre and I'll choose you a good one ;)")
    input()
    print(' 1 Horror  \n 2 Comedy \n 3 Action \n 4 Romance \n 5 Drama \n 6 Adventure  \n 7 Science fiction \n 8 Fantasy\n')

    genero = (input('Enter a number or genre: '))

    if genero == "1" or genero == "horror" or genero == "Horror":
        {
            print("\nI don't really like horror movies, but maybe you might like it.\n\n{}".format(random.choice(listat)))}
    elif genero == "2" or genero == "comedy" or genero == "Comedy":
        {
            print("\nI've had a lot of laughs throughout my life with comedy movies.\n\n{}".format(random.choice(listac)))}
    elif genero == "3" or genero == "action" or genero == "Action":
        {
            print('\nI love frantic action movies.\n\n{}'.format(random.choice(listaa)))}
    elif genero == "4" or genero == "romance" or genero == "Romance":
        {
            print('\nWatching this kind of movie I remember my old companion.\n\n{}'.format(random.choice(listar)))}
    elif genero == "5" or genero == "drama" or genero == "Drama":
        {
            print('\nI think this is a choice you might like.\n\n{}'.format(random.choice(listad)))}
    elif genero == "6" or genero == "adventure" or genero == "Adventure":
        {
            print('\nI think we all like an adventure.\n\n{}'.format(random.choice(listaav)))}
    elif genero == "7" or genero == "science fiction" or genero == "Science Fiction":
        {
            print('\nThis is my favorite genre. I would like to participate in a movie.\n\n{}'.format(random.choice(listaf)))}
    elif genero == "8" or genero == "fantasy" or genero == "Fantasy":
        {
            print('\nWhen I was a padawan I watched a lot of fantasy movies.\n\n{}'.format(random.choice(listafa)))}
    else:
        {
            print('\nInvalid option')}

    print("\nWhat do you think?")
    cont = input(
        "Y.Maybe another title would be better!?\nN.It's definitely a good one, thank you!\n(Y/N) ")
    if cont == "Y" or cont == "y" or cont == "yes" or cont == "Yes" or cont == "YES":
        {
            print("\nLet's do it!")}
        continue
    else:
        {print()}

        break

if usuarioId < 18:
    {
        print("It was my pleasure young padawan, see you soon in a next mission! \nMay the force be with you!")
    }

elif usuarioId >= 18:
    {
        print("It was my pleasure young jedi, see you soon in a next mission! \nMay the force be with you!")
    }

input()
